	<!--[if lte IE 8]>
		<script type="text/javascript">
			var htmlshim='abbr,article,aside,audio,canvas,details,figcaption,figure,footer,header,mark,meter,nav,output,progress,section,summary,time,video'.split(',');
			var htmlshimtotal=htmlshim.length;
			for(var i=0;i<htmlshimtotal;i++) document.createElement(htmlshim[i]);
		</script>
	<![endif]-->
	<script>
		//CODIGO DO GOOGLE ANALYTICS
	</script>
