	<header>
		<div id="logo">
			<a href="index.php" title="Salão de Beleza"><h1>Salão de Beleza</h1></a>
		</div>
		<nav>
			<ul>
				<li><a href="#" title="Espaço">Espaço</a></li>
				<li><a href="#" title="Beleza">Beleza</a></li>
				<li><a href="#" title="Noivas">Noivas</a></li>				
				<li><a href="#" title="Barbearia">Barbearia</a></li>
				<li><a href="#" title="Contato">Contato</a></li>
			</ul>
		</nav>
	</header>