	<footer>
		<div id="logo">
			<a href="#" title="Salão de Beleza"><h1>Salão de Beleza</h1></a>
		</div>
		<div>
			<nav>
				<ul>
					<li><a href="#" class="sociais_face"><span>Facebook</span></a></li>
					<li><a href="#" class="sociais_inst"><span>Instagram</span></a></li>
					<li><a href="#" class="sociais_yout"><span>Youtube</span></a></li>
				</ul>
			</nav>
			<!-- SEP -->
			<div id="endereco">
				<div>
					<a href="#" class="mapa" title="Onde estamos"><span>Onde estamos</span></a>
				</div>
				<div>
					<p>R. Sem Nome, 00 • Bairro • Cidade/Estado</p>
					<p>3232-3232 • 99999-8888<img class="whats" src="css/logo_whastapp.png" alt="Whatsapp"></p>
				</div>
			</div>
			<!-- SEP -->
			<div id="fique_ligado">
				<h2>Fique por dentro!</h2>
				<p>Receba e-mails com promoções e novidades do Salão de Beleza:</p>
				<form>
				<!--action="fique-por-dentro.php" method="POST"-->
					<input type="text" name="email" id="email" />
					<button>Enviar</button>
				</form>
			</div>
			<div id="brainstorming">
				<p>Desenvolvido por	<a href="www.labweb.com.br">LabWeb</a></p>
			</div>
		</div>
	</footer>